spring:
  application:
    name: chatbot-backend
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DB}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
